CREATE USER 'm133'@'localhost' IDENTIFIED BY 'm133';

DROP DATABASE m133;
CREATE DATABASE m133;
USE m133;

GRANT ALL PRIVILEGES ON user TO 'm133'@'localhost';

CREATE TABLE poll (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
	closed BOOLEAN
);

CREATE TABLE vote (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    response BOOLEAN,
	poll_id INT,
	FOREIGN KEY (poll_id) REFERENCES poll(id)
);